# **Reshaping Array**
Reshaping means chaning the shape of an array.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
#1D to 2D array
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#1D to 3D array
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# **Array indexing**
Array indexing is the same as accessing an array element.
You can access an array element by refering to its index number.

In [ ]:
arr = np.array([1,2,3,4])
print(arr[1])

2


In [ ]:
print(arr[2]+arr[3])    #addition of two array elements

7


In [18]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])      #accessing 2D array

In [20]:
print(arr[0,2])     #1st row 3rd element.....
print(arr[1,4])       #2nd row 5th element.....

3
10


In [22]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])     #accessing 3D array.....

In [25]:
print(arr[0,0,2])       #1th martix 1nd row 3rd column....
print(arr[1,1,0])         #2nd martix 2nd row 1st column....

3
10
